name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag djborad/curd-demo:tagname
      - name: push image to docker hub
        run: |
          docker login -u djborad -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push djborad/curd-demo:tagname
